esphome:
  name: ceilingLight
  platform: ESP8266
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Create a switch for safe_mode in order to flash the device
# Solution from this thread:
# https://community.home-assistant.io/t/esphome-flashing-over-wifi-does-not-work/357352/1
switch:
  - platform: safe_mode
    name: "Flash Mode (Safe Mode)"

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  reboot_timeout: 15min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ceiling Light Fallback Hotspot"
    password: !secret fallback_ssid_password

captive_portal:

light:
  - platform: rgbww
    name: "Ceiling Light"
    red: red
    green: green
    blue: blue
    cold_white: cold_white
    warm_white: warm_white
    # color temperature not calibrated!
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K

output:
  - platform: esp8266_pwm
    id: red
    pin: GPIO15
  - platform: esp8266_pwm
    id: green
    pin: GPIO14
  - platform: esp8266_pwm
    id: blue
    pin: GPIO12
  - platform: esp8266_pwm
    id: cold_white
    pin: GPIO4
  - platform: esp8266_pwm
    id: warm_white
    pin: GPIO13
    